# use elasticsearch 1.4.4 base container
# see https://github.com/docker-library/elasticsearch/blob/03a5bda1ff2d27b000e5236082b26975a6a44c2e/1.4/Dockerfile
FROM elasticsearch:1.4.4

# overrides default configuration file shipped by base image
ADD elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

